CUDA_VISIBLE_DEVICES=0, \
swift sft \
    --model /fred/oz337/zdeng/ms-swift/llava-1.5-7b-hf/models/swift/llava-1.5-7b-hf \
    --model_type llava1_5_hf \
    --train_type full \
    --dataset '/fred/oz337/zdeng/prompt_stealing_ours/data/lexica_dataset/train5_modified.json' \
    --split_dataset_ratio 0.0001 \
    --torch_dtype bfloat16 \
    --num_train_epochs 0.001 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 1e-5 \
    --gradient_accumulation_steps 1 \
    --eval_steps 100000 \
    --save_steps 10 \
    --save_total_limit 5 \
    --logging_steps 5 \
    --max_length 2048 \
    --output_dir /fred/oz337/zdeng/MS-SWIFT/output \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --model_author swift \
    --model_name swift-robot
